### DISCUSSION TITLE
questions about  power_id: powermeter0

### DISCUSSION THREAD

**Discussion by koosoli** [syssi/esphome-soyosource-gtn-virtual-meter#131] [Q&A]
Hello, first of all thanks for doing this project!
Quick question; In the code there is this line:     
```
# The state of this sensor (instantaneous power in watt) is used as source
    power_id: powermeter0
```
In home assistant I configured a Sensor that gives me the current values of the power meter (negative values are surplus power):

```
sensor.power_used
-0.086	unit_of_measurement: kW
friendly_name: Power-Used
```

so can I just write in the ESP config it like so? :
```
# The state of this sensor (instantaneous power in watt) is used as source
    power_id: sensor.power_used
```
Thanks

**Comment by syssi** [comment]
If the sensor measurement isn't available at the ESP already you have to import the Home Assistant entity first:

https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/blob/main/powermeter-sensor-examples/homeassistant-native-api.yaml

```
api:

sensor:
  - platform: homeassistant
    id: powermeter0
    name: "Instantaneous Power"
    entity_id: sensor.power_used
    filters:
      - throttle_average: 15s
```

As soon the sensor measurement is available as local sensor you should apply the `id: powermeter0` here.

**Reply by koosoli** [reply]
Thanks, so I have to add this lines to the ESP code?
Are there guidelines if the value has to be in Watts or KiloWatts?  
Update: stupid question, it is watts and was in the code comment

After I successfully configure this, will the soyo then auto-limit its output if I have surplus power, or do I have to make an automation for that?

thanks

**Reply by syssi** [reply]
> Are there guidelines if the value has to be in Watts or KiloWatts?

If you want to aggregate the power to energy you have to use the `total_daily_energy` component:

```
time:
  - platform: sntp
    id: my_time

sensor:
  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    battery_power:
      name: "${inverter0} battery power"
      id: inverter0_power
      filters:
        - median:
            window_size: 5
            send_every: 3
            send_first_at: 3

  - platform: total_daily_energy
    name: "${inverter0} energy today"
    icon: mdi:counter
    power_id: inverter0_power
    accuracy_decimals: 3
    unit_of_measurement: kWh
    restore: true
    filters:
      - multiply: 0.001
```

**Reply by syssi** [reply]
> After I successfully configure this, will the soyo then auto-limit its output if I have surplus power, or do I have to make an automation for that?

Yes. As soon as you feed the virtual limiter with your smartmeter measurements the component will control the power output of the Soyosource and tries to optimize your energy bill. ;-)

**Reply by koosoli** [reply]
Cool!

I am not sure about these settings, do i need them?
```
    # Optional settings
    power_sensor_inactivity_timeout: 20s
    power_demand_calculation: NEGATIVE_MEASUREMENTS_REQUIRED
    min_power_demand: 0
    max_power_demand: 900
    zero_output_on_min_power_demand: true
```
Since my sensor is giving me the calculated watts already (negative being surplus)

**Reply by syssi** [reply]
1. `power_sensor_inactivity_timeout`: The component turns the Soyosource off after 20 seconds if there are no smartmeter measurements telling the current power demand
2. `power_demand_calculation`: The is the correct calculation method for your smartmeter because this calculation methods requires negative measurements if power is exported
3. `min_power_demand` + `zero_output_on_min_power_demand`: If no power is needed the Soyosource is turned off (power_output: 0W)
4. `max_power_demand`: The component is allowed to ask the Soyosource to feed 900W to the grid.

**Reply by syssi** [reply]
No change needed here if your smartmeter is able to provide more than 1 sensor update per 20 seconds.

**Reply by koosoli** [reply]
> No change needed here if your smartmeter is able to provide more than 1 sensor update per 20 seconds.

ok, perfect. That sensor should update every 10 seconds.

Perfect, then I think I am ready to flash:

```
substitutions:
  name: soyosource-gtn-virtual-meter
  device_description: "Monitor a Soyosource GTN and control the power output on demand both via RS485"
  external_components_source: github://syssi/esphome-soyosource-gtn-virtual-meter@main
  tx_pin: GPIO1
  rx_pin: GPIO3

esphome:
  name: soyo1
  friendly_name: soyo1
  comment: ${device_description}
  project:
    name: "syssi.esphome-soyosource-gtn-virtual-meter"
    version: 2.1.0

esp8266:
  board: d1_mini_pro

external_components:
  - source: ${external_components_source}
    refresh: 0s


# Enable logging
logger:


ota:
  password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Soyo1 Fallback Hotspot"
    password: "xxx"

captive_portal:


# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

uart:
  - id: uart0
    baud_rate: 4800
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

soyosource_modbus:
  - id: modbus0
    uart_id: uart0
    # flow_control_pin: GPIO12

    # Optional settings
    #
    # The name is used as prefix for some log messages and should
    # help to distinguish between different instances/devices
    name: 1000wsoyo1_inverter

soyosource_virtual_meter:
  - id: virtualmeter0
    soyosource_modbus_id: modbus0

sensor:
  - platform: homeassistant
    id: powermeter0
    name: "Instantaneous Power"
    entity_id: sensor.power_used_w
    filters:
      - throttle_average: 10s

    # The state of this sensor (instantaneous power in watt) is used as source
    power_id: powermeter0

    update_interval: 10s  **-> this is how often my sensor updates, hope this is correct**

soyosource_inverter:
  - id: inverter0
    soyosource_modbus_id: modbus0

binary_sensor:
  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    fan_running:
      name: "${name} fan running"

number:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    buffer:
      name: "${name} buffer"
      initial_value: 10
      restore_value: true
    manual_power_demand:
      name: "${name} manual power demand"
      max_value: 900
    max_power_demand:
      name: "${name} max power demand"
      initial_value: 600
      max_value: 900
      restore_value: true
    power_demand_divider:
      name: "${name} power demand divider"
      initial_value: 1
      restore_value: true

sensor:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    power_demand:
      name: "${name} power demand"

  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    operation_status_id:
      name: "${name} operation status id"
      id: operation_status_id0
    battery_voltage:
      name: "${name} battery voltage"
    battery_current:
      name: "${name} battery current"
    battery_power:
      name: "${name} battery power"
    ac_voltage:
      name: "${name} ac voltage"
    ac_frequency:
      name: "${name} ac frequency"
    temperature:
      name: "${name} temperature"



switch:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    manual_mode:
      name: "${name} manual mode"
      restore_mode: RESTORE_DEFAULT_ON
    emergency_power_off:
      name: "${name} emergency power off"
      restore_mode: RESTORE_DEFAULT_OFF

text_sensor:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    operation_mode:
      name: "${name} limiter operation mode"

  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    operation_status:
      name: "${name} operation status"
```

**Reply by syssi** [reply]
I've made some minor fixes:

1. Multiple `sensor:` sections aren't allowed/possible
2. You have to parameterize the `soyosource_virtual_meter` component not the power sensor.
3. You have to stick to the `NEGATIVE_MEASUREMENTS_REQUIRED` method. The default doesn't work for you.

```
substitutions:
  name: soyosource-gtn-virtual-meter
  device_description: "Monitor a Soyosource GTN and control the power output on demand both via RS485"
  external_components_source: github://syssi/esphome-soyosource-gtn-virtual-meter@main
  tx_pin: GPIO1
  rx_pin: GPIO3

esphome:
  name: soyo1
  friendly_name: soyo1
  comment: ${device_description}
  project:
    name: "syssi.esphome-soyosource-gtn-virtual-meter"
    version: 2.1.0

esp8266:
  board: d1_mini_pro

external_components:
  - source: ${external_components_source}
    refresh: 0s


# Enable logging
logger:


ota:
  password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Soyo1 Fallback Hotspot"
    password: "xxx"

captive_portal:


# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

uart:
  - id: uart0
    baud_rate: 4800
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

soyosource_modbus:
  - id: modbus0
    uart_id: uart0
    # flow_control_pin: GPIO12

    # Optional settings
    #
    # The name is used as prefix for some log messages and should
    # help to distinguish between different instances/devices
    name: 1000wsoyo1_inverter

soyosource_virtual_meter:
  - id: virtualmeter0
    soyosource_modbus_id: modbus0
    power_id: powermeter0
    power_demand_calculation: NEGATIVE_MEASUREMENTS_REQUIRED
    update_interval: 3s

soyosource_inverter:
  - id: inverter0
    soyosource_modbus_id: modbus0

binary_sensor:
  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    fan_running:
      name: "${name} fan running"

number:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    buffer:
      name: "${name} buffer"
      initial_value: 10
      restore_value: true
    manual_power_demand:
      name: "${name} manual power demand"
      max_value: 900
    max_power_demand:
      name: "${name} max power demand"
      initial_value: 600
      max_value: 900
      restore_value: true
    power_demand_divider:
      name: "${name} power demand divider"
      initial_value: 1
      restore_value: true

sensor:
  - platform: homeassistant
    id: powermeter0
    name: "Instantaneous Power"
    entity_id: sensor.power_used_w
    filters:
      - throttle_average: 10s

  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    power_demand:
      name: "${name} power demand"

  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    operation_status_id:
      name: "${name} operation status id"
      id: operation_status_id0
    battery_voltage:
      name: "${name} battery voltage"
    battery_current:
      name: "${name} battery current"
    battery_power:
      name: "${name} battery power"
    ac_voltage:
      name: "${name} ac voltage"
    ac_frequency:
      name: "${name} ac frequency"
    temperature:
      name: "${name} temperature"

switch:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    manual_mode:
      name: "${name} manual mode"
      restore_mode: RESTORE_DEFAULT_ON
    emergency_power_off:
      name: "${name} emergency power off"
      restore_mode: RESTORE_DEFAULT_OFF

text_sensor:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    operation_mode:
      name: "${name} limiter operation mode"

  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    operation_status:
      name: "${name} operation status"
```
