### DISCUSSION TITLE
Integrate the Batterie connected to the Soyo into Home Assisant Energy Dashboard

### DISCUSSION THREAD

**Discussion by koosoli** [syssi/esphome-soyosource-gtn-virtual-meter#132] [Q&A]
Hi,

I would like to integrate the Batterie information that is connected to the soyo into the Home Assistant Energy Dashboard (https://www.home-assistant.io/docs/energy/battery/) 

As my batterie has no API, I think the best next thing is to do it via this project (if even possible). 
But for this to work, I would need separate information on what is going into the batterie and what is coming out of it, but how will I be able to make the difference on input and output with only these? :

```
   battery_voltage:
      name: "${name} battery voltage"
    battery_current:
      name: "${name} battery current"
    battery_power:
      name: "${name} battery power"
```
Thanks
