### DISCUSSION TITLE
Update rate / Aktualisierungsrate

### DISCUSSION THREAD

**Discussion by sorz2122** [syssi/esphome-soyosource-gtn-virtual-meter#152] [General]
Hello, is it possible to limit the update rate of the SOYO to 3 seconds? Currently, it only receives a feed value every 15 seconds, which I find a bit long as the feed fluctuation at my end often reaches around +- 100 watts.

Best regards.

German:
Hallo, ist es möglich, die aktualisierungsrate des SOYO auf 3 Sekunden zu begrenzen? Aktuell bekommt dieser nur alle 15 Sekunden einen einspeisewert zugesendet, das erachte ich für etwas lange da die Eispeisung bei mir oft dann +- 100 Watt beträgt. 
Liebe Grüße.

**Comment by syssi** [comment]
Take a look at the `powermeter0` definition:

```
  # mqtt subscribe example
  - id: powermeter0
    internal: true
    platform: mqtt_subscribe
    name: "${name} instantaneous power consumption"
    topic: "smartmeter/sensor/groundfloor/obis/1-0:16.7.0/255/value"
    accuracy_decimals: 2
    unit_of_measurement: W
    device_class: power
    filters:
      - throttle_average: 15s
```

https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/blob/main/esp8266-example.yaml#L139-L149

The `throttle_average: 15s` is responsible for the delay. If you remove the filter the value is passed to the `soyosource_virtual_meter` on every update instantly.
