### DISCUSSION TITLE
how to change the "slider" to normal input fields

### DISCUSSION THREAD

**Discussion by Rubber1Duck** [syssi/esphome-soyosource-gtn-virtual-meter#169] [Q&A] [answered]
The slider to change some values (e.g. for buffer, max demand etc) are not very suitable on mobile screens, for my opinion. What i have to change in the yaml file (or other files) to change this to a normal input field? Where i can find the definitions for that?

**Comment by syssi** [comment]
Take a look at the documentation of the `number` entity. You are looking for the `mode` parameter. Just pass the value `box` here: https://esphome.io/components/number/

**Reply by syssi** [reply, marked as answer]
```
number:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    buffer:
      name: "${name} buffer"
      initial_value: 10
      restore_value: true
      mode: box
    manual_power_demand:
      name: "${name} manual power demand"
      max_value: 900
      mode: box
    max_power_demand:
      name: "${name} max power demand"
      initial_value: 600
      max_value: 900
      restore_value: true
      mode: box
    power_demand_divider:
      name: "${name} power demand divider"
      initial_value: 1
      restore_value: true
      mode: box
```
