### ISSUE TITLE
Control "power_demand_divider" and "buffer" using automations

### ISSUE THREAD

**Issue by syssi** [syssi/esphome-soyosource-gtn-virtual-meter#112]
### Discussed in https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/discussions/111

<div type='discussions-op-text'>

<sup>Originally posted by **pfeupfeu** March  7, 2023</sup>
Since yersterday my setup is working! Now I would like to implement small improvements.

In winter, with little solar yield, only one of my 3 Soyos should run to get a better efficency. 
In summer, when there is "too much" solar yield, I would like to overfeed into the grid.

Therefore, I would like to be able to change the "power_demand_divider" and the "buffer" value without reflashing. 
Does anyone have a tip on how I can achieve this? </div>

**Comment by syssi** [comment]
@pfeupfeu I've created an issue. This helps me to track the progress of the new feature.

**Comment by syssi** [comment]
Please update your `number` component section to:

```
number:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    buffer:
      name: "${name} buffer"
      initial_value: 10
      restore_value: true
    manual_power_demand:
      name: "${name} manual power demand"
      max_value: 900
    max_power_demand:
      name: "${name} max power demand"
      initial_value: 600
      max_value: 900
      restore_value: true
    power_demand_divider:
      name: "${name} power demand divider"
      initial_value: 1
      restore_value: true
```

There are two new number entities available now if you are using the `main` branch of the external component.
