### ISSUE TITLE
Prevent overshooting (esp32 go down)? 

### ISSUE THREAD

**Issue by Giro-S** [syssi/esphome-soyosource-gtn-virtual-meter#182]
Hello to all :)
I have a problem with overshooting very frequent, I tried to change many settings in esphome but without results :/

I have 3 inverters with 1 rs485 bus for to sync them, esp32 mini pilot them
The three circuits are the same:  PV-->MPPT(epever)-->battery-->inverter

This is an yesterday example from 12AM to 5 PM; the main counter sends signails every 3 seconds:
![Screenshot 2024-07-28 104236](https://github.com/user-attachments/assets/f3053183-6dd6-42cd-8f04-9e153db959a9)

These are the power of inverters:
![Screenshot 2024-07-28 103932](https://github.com/user-attachments/assets/2eb1c0d4-b11a-48bb-91a0-5b9671fba90f)
![Screenshot 2024-07-28 103959](https://github.com/user-attachments/assets/b6cbe448-ca37-45a5-b092-4137d4da422e)
![Screenshot 2024-07-28 104025](https://github.com/user-attachments/assets/56388d7a-b427-4239-aa0b-bea7103868b2)

Every ~2 minutes the esp32 go down and after go powershooting :/
How to solve this problem?

In the code i tried many values on virtual meter update_interval: 3 sec, 2 sec, 1 sec and 0.5sec
On soyosource_display update_interval tried 5, 6, 7, 8 sec

```
soyosource_virtual_meter:
  - id: virtualmeter0
    soyosource_modbus_id: modbus0
    power_id: powermeter0
    power_sensor_inactivity_timeout: 20s
    power_demand_calculation: NEGATIVE_MEASUREMENTS_REQUIRED
    min_power_demand: 0
    max_power_demand: 2700
    zero_output_on_min_power_demand: true
    power_demand_divider: 3
    buffer: 0
    operation_status_id: operation_status_id0
    update_interval: 0.5s

soyosource_display:
  - id: display1
    uart_id: i2c_uart_0
    protocol_version: SOYOSOURCE_WIFI_VERSION
    update_interval: 8s
  - id: display2
    uart_id: i2c_uart_1
    protocol_version: SOYOSOURCE_WIFI_VERSION
    update_interval: 8s
  - id: display3
    uart_id: uart_1
    protocol_version: SOYOSOURCE_WIFI_VERSION
    update_interval: 8s
```

**Comment by syssi** [comment]
Could you provide a ESPHome log (with log level `DEBUG`) too? The implementation should report some important details here.

**Comment by syssi** [comment]
The `update_interval` of the `soyosource_virtual_meter` must be less fast as your smart meter measurements. If you smartmeter publishs a new value every 3 seconds you should use an `update_interval` of around 6s.

Are you able to change the update interval of your smartmeter to `1s`? In this case a `3s` update interval of the `soyosource_virtual_meter` could be a good choice.

**Comment by Giro-S** [comment]
Thank you Sebastian :)

> Could you provide a ESPHome log (with log level `DEBUG`) too? The implementation should report some important details here.

Ok, enabled it

> The `update_interval` of the `soyosource_virtual_meter` must be less fast as your smart meter measurements. If you smartmeter publishs a new value every 3 seconds you should use an `update_interval` of around 6s.

Ok, set it to 6sec
> Are you able to change the update interval of your smartmeter to `1s`? In this case a `3s` update interval of the `soyosource_virtual_meter` could be a good choice.

Sorry, no, minimum update is 3 seconds.
This is my meter, works with local tuya
![41CIm5glB6L _SR600,315_PIWhiteStrip,BottomLeft,0,35_SCLZZZZZZZ_FMpng_BG255,255,255](https://github.com/user-attachments/assets/de650341-b578-4b28-bb4f-a084b1637e31)

Can you tell me one that report every second or less without wires? If I use PZEM004T with esphome and set ever 1 second ...should it acceptable?

and this value on 5 seconds?

```
soyosource_display:
  - id: display1
    uart_id: i2c_uart_0
    protocol_version: SOYOSOURCE_WIFI_VERSION
    update_interval: 8s
```
