### ISSUE TITLE
Component not found: soyosource_modbus.

### ISSUE THREAD

**Issue by ASAS443** [syssi/esphome-soyosource-gtn-virtual-meter#208]
Gerne hilfe, was ich tun mus
Danke Andre

```
INFO Unable to import component soyosource_modbus: No module named 'esphome.components.soyosource_modbus'
Failed config

soyosource_modbus: [source /config/esphome/soyosource-gtn-virtual-meter.yaml:61]
  
  Component not found: soyosource_modbus.
  - id: modbus0
    uart_id: uart_0
    name: firstfloor_inverter
```

**Comment by syssi** [comment]
Kannst du deine vollständige YAML-Konfiguration zur Verfügung stellen? Ich würde mit dieser gerne versuchen das Problem zu repduzieren. Welche ESPHome Core Version nutzt du?

**Comment by ASAS443** [comment]
Gerne.
Ich habe es auch met ESP32-C3 probiert und gab das selbe problem.

ubstitutions:
  name: soyosource-gtn-virtual-meter
  device_description: "Monitor a Soyosource GTN and control the power output on demand both via RS485"
  external_components_source: github://syssi/esphome-soyosource-gtn-virtual-meter@main

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-soyosource-gtn-virtual-meter"
    version: 2.2.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Rf8PsdyMqYN1doQ3Bg3ExVXmR35uvyZGXisBw9M7gdM="

ota:
  - platform: esphome
    password: "e86f7661477ca35e88ba7905781b9b86"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.2.54
    gateway: 192.168.2.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Soyosource-Gtn-Virtual-Meter"
    password: "BNIGPCtobaQM"

captive_portal:


uart:
  - id: uart_0
    baud_rate: 4800
    # tx_pin: ${tx_pin}
    # rx_pin: ${rx_pin}
    tx_pin: TX
    rx_pin: RX

Soyosource_modbus:
  - id: modbus0
    uart_id: uart_0
    name: firstfloor_inverter

soyosource_virtual_meter:
  - id: virtualmeter0
    soyosource_modbus_id: modbus0

    # The state of this sensor (instantaneous power in watt) is used as source
    power_id: powermeter0

    # Optional settings
    power_sensor_inactivity_timeout: 20s
    power_demand_calculation: NEGATIVE_MEASUREMENTS_REQUIRED
    min_power_demand: 0
    max_power_demand: 900
    zero_output_on_min_power_demand: true
    # Split/distribute the power demand if you have multiple inverters attached to the same RS485 bus
    power_demand_divider: 1
    # A positive buffer value (10) tries to avoid exporting power to the grid (demand - 10 watts)
    # A negative buffer value (-10) exports power to the grid (demand + 10 watts)
    buffer: 10
    # The operation_status_id sensor is expected here. Passing the operation_status won't work
    # The state is used to suspend the limiter if the operation status of the inverter isn't 0x0 (normal)
    # operation_status_id: operation_status_id0

    # The update interval is important and defaults to 3 seconds. If the demand is sent too frequently
    # or rarely the interverter stops. TODO: Identify and validate the lower and upper update limit
    update_interval: 3s

soyosource_inverter:
  - id: inverter0
    soyosource_modbus_id: modbus0

binary_sensor:
  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    fan_running:
      name: "${name} fan running"

number:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    buffer:
      name: "${name} buffer"
      initial_value: 10
      restore_value: true
    manual_power_demand:
      name: "${name} manual power demand"
      max_value: 900
    max_power_demand:
      name: "${name} max power demand"
      initial_value: 600
      max_value: 900
      restore_value: true
    power_demand_divider:
      name: "${name} power demand divider"
      initial_value: 1
      restore_value: true

sensor:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    power_demand:
      name: "${name} power demand"

  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    operation_status_id:
      name: "${name} operation status id"
      id: operation_status_id0
    battery_voltage:
      name: "${name} battery voltage"
    battery_current:
      name: "${name} battery current"
    battery_power:
      name: "${name} battery power"
    ac_voltage:
      name: "${name} ac voltage"
    ac_frequency:
      name: "${name} ac frequency"
    temperature:
      name: "${name} temperature"

  # mqtt subscribe example
  - id: powermeter0
    internal: true
    platform: mqtt_subscribe
    name: "${name} instantaneous power consumption"
    topic: "smartmeter/sensor/groundfloor/obis/1-0:16.7.0/255/value"
    accuracy_decimals: 2
    unit_of_measurement: W
    device_class: power
    filters:
      - throttle_average: 15s

#   # import smartmeter reading from homeassistant
#   # requires the "api" component see above
#   - platform: homeassistant
#     id: powermeter0
#     name: "${name} smartmeter instantaneous power"
#     entity_id: sensor.firstfloor_smartmeter_instantaneous_power
#     filters:
#       - throttle_average: 15s

switch:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    manual_mode:
      name: "${name} manual mode"
      restore_mode: RESTORE_DEFAULT_ON
    emergency_power_off:
      name: "${name} emergency power off"
      restore_mode: RESTORE_DEFAULT_OFF

text_sensor:
  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    operation_status:
      name: "${name} operation status"

  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    operation_mode:
      name: "${name} limiter operation mode"

**Comment by ASAS443** [comment]
Validation 
INFO ESPHome 2025.7.0-dev
INFO Reading configuration /config/esphome/soyosource-gtn-virtual-meter.yaml...
ERROR Error while reading config: Invalid YAML syntax:

Secret 'mqtt_host' not defined
  in "/config/esphome/soyosource-gtn-virtual-meter.yaml", line 32, column 11


# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
This section made me think I don't need to use MQTT. because I use HA.

**Comment by syssi** [comment]
This is correct. If you remove the `mqtt` section you have to remove this section too:

```
  # mqtt subscribe example
  - id: powermeter0
    internal: true
    platform: mqtt_subscribe
    name: "${name} instantaneous power consumption"
    topic: "smartmeter/sensor/groundfloor/obis/1-0:16.7.0/255/value"
    accuracy_decimals: 2
    unit_of_measurement: W
    device_class: power
    filters:
      - throttle_average: 15s
```

Do you have the smartmeter power consumption measurement as Home Assistant sensor entity available? You could subscribe to this sensor using the native API:

```
   # import smartmeter reading from homeassistant
   # requires the "api" component see above
   - platform: homeassistant
     id: powermeter0
     name: "${name} smartmeter instantaneous power"
     entity_id: sensor.firstfloor_smartmeter_instantaneous_power
     filters:
       - throttle_average: 15s
```

You have to replace `sensor.firstfloor_smartmeter_instantaneous_power` with your smartmeter entity.

**Comment by syssi** [comment]
You can use this project to control the power output of the inverter manually. If you want to use the dynamic output power automatism (zero-export behaviour) you have to feed the current power consumption into the component.

**Comment by ASAS443** [comment]
Aha,, for getting experiense.  I would like to start with controll the menually power output.  Is this possible with the project with some changes?

**Comment by syssi** [comment]
Just add a template sensor as dummy to the YAML and use the manual mode only:

```
  - platform: template
    name: "${name} instantaneous power consumption"
    id: powermeter0
    internal: true
    lambda: |-
      return 0.0;
    update_interval: never
```

**Comment by syssi** [comment]
```
substitutions:
  name: soyosource-gtn-virtual-meter
  device_description: "Monitor a Soyosource GTN and control the power output on demand both via RS485"
  external_components_source: github://syssi/esphome-soyosource-gtn-virtual-meter@main

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-soyosource-gtn-virtual-meter"
    version: 2.2.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Rf8PsdyMqYN1doQ3Bg3ExVXmR35uvyZGXisBw9M7gdM="

ota:
  - platform: esphome
    password: "e86f7661477ca35e88ba7905781b9b86"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.2.54
    gateway: 192.168.2.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Soyosource-Gtn-Virtual-Meter"
    password: "BNIGPCtobaQM"

captive_portal:


uart:
  - id: uart_0
    baud_rate: 4800
    # tx_pin: ${tx_pin}
    # rx_pin: ${rx_pin}
    tx_pin: TX
    rx_pin: RX

soyosource_modbus:
  - id: modbus0
    uart_id: uart_0
    name: firstfloor_inverter

soyosource_virtual_meter:
  - id: virtualmeter0
    soyosource_modbus_id: modbus0

    # The state of this sensor (instantaneous power in watt) is used as source
    power_id: powermeter0

    # Optional settings
    power_sensor_inactivity_timeout: 20s
    power_demand_calculation: NEGATIVE_MEASUREMENTS_REQUIRED
    min_power_demand: 0
    max_power_demand: 900
    zero_output_on_min_power_demand: true
    # Split/distribute the power demand if you have multiple inverters attached to the same RS485 bus
    power_demand_divider: 1
    # A positive buffer value (10) tries to avoid exporting power to the grid (demand - 10 watts)
    # A negative buffer value (-10) exports power to the grid (demand + 10 watts)
    buffer: 10
    # The operation_status_id sensor is expected here. Passing the operation_status won't work
    # The state is used to suspend the limiter if the operation status of the inverter isn't 0x0 (normal)
    # operation_status_id: operation_status_id0

    # The update interval is important and defaults to 3 seconds. If the demand is sent too frequently
    # or rarely the interverter stops. TODO: Identify and validate the lower and upper update limit
    update_interval: 3s

soyosource_inverter:
  - id: inverter0
    soyosource_modbus_id: modbus0

binary_sensor:
  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    fan_running:
      name: "${name} fan running"

number:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    buffer:
      name: "${name} buffer"
      initial_value: 10
      restore_value: true
    manual_power_demand:
      name: "${name} manual power demand"
      max_value: 900
    max_power_demand:
      name: "${name} max power demand"
      initial_value: 600
      max_value: 900
      restore_value: true
    power_demand_divider:
      name: "${name} power demand divider"
      initial_value: 1
      restore_value: true

sensor:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    power_demand:
      name: "${name} power demand"

  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    operation_status_id:
      name: "${name} operation status id"
      id: operation_status_id0
    battery_voltage:
      name: "${name} battery voltage"
    battery_current:
      name: "${name} battery current"
    battery_power:
      name: "${name} battery power"
    ac_voltage:
      name: "${name} ac voltage"
    ac_frequency:
      name: "${name} ac frequency"
    temperature:
      name: "${name} temperature"

  - platform: template
    name: "${name} instantaneous power consumption"
    id: powermeter0
    internal: true
    lambda: |-
      return 0.0;
    update_interval: never

switch:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    manual_mode:
      name: "${name} manual mode"
      restore_mode: RESTORE_DEFAULT_ON
    emergency_power_off:
      name: "${name} emergency power off"
      restore_mode: RESTORE_DEFAULT_OFF

text_sensor:
  - platform: soyosource_inverter
    soyosource_inverter_id: inverter0
    operation_status:
      name: "${name} operation status"

  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    operation_mode:
      name: "${name} limiter operation mode"
```
