### ISSUE TITLE
Add a better power demand calculation for positive-only smartmeter measurements

### ISSUE THREAD

**Issue by syssi** [syssi/esphome-soyosource-gtn-virtual-meter#26]
In case of positive-only smartmeter measurements the virtual meter is blind at the left limit of the range.

Example scenario:

1. There is a consumer like a fridge using 500W for a few minutes
2. The virtual meter will report a demand of 500W & the inverter delivers the 500W
3. The smartmeter reports a grid import of 0 W
4. If the fridge turns off the measurement of the smartmeter won't change: 0W
5. We are exporting 500W to the grid now.

Goal: Try to minimize the time and the power exporting to the grid without knowing how much power is exported

If your smartmeter supports negative measurements / indicates exporting to the grid by a negative sign please use:

```
soyosource_virtual_meter:
  power_id: powermeter
  power_sensor_inactivity_timeout: 20s
  power_demand_calculation: NEGATIVE_MEASUREMENTS_REQUIRED
```
