### ISSUE TITLE
MQTT Update interval

### ISSUE THREAD

**Issue by careyer** [syssi/esphome-soyosource-gtn-virtual-meter#72]
Hey @syssi,

sorry for bugging you again... but I have a problem that I don't have a clue on how to solve.
My PowerSensor is sensing and sending the required power every 5s via MQTT.... However the esphome-soyosource-gtn-virtual-meter does only read a new value via MQTT every 60sec or so....
Is there a way to speed up the MQTT and process the incomming MQTT Messages faster?

![mqtt](https://user-images.githubusercontent.com/6156251/189532079-da5dc3b6-2068-4c17-9fb1-743cec99d9a9.JPG)

Thanks for your help!

**Comment by syssi** [comment]
Could you provide your yaml configuration? It looks like you are throttling the incoming MQTT messages. Something like this:

```
  - id: powermeter
    internal: true
    platform: mqtt_subscribe
    name: "${name} instantaneous power consumption"
    topic: "smartmeter/sensor/groundfloor/obis/1-0:16.7.0/255/value"
    accuracy_decimals: 2
    unit_of_measurement: W
    device_class: power
    filters:
      - throttle_average: 60s
```

The ESPHome node does receive all subscribed topics immediately per default. Please be careful if you play around with these parameters. You will create oscillations if you update the power demand too often.
