### ISSUE TITLE
Mulitple inverters on the same RS485 bus

### ISSUE THREAD

**Issue by DL6ER** [syssi/esphome-soyosource-gtn-virtual-meter#86]
https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/commit/2c7a73fb43bf7c00d7e523c09e80bbb5acd78878 implemented a power divider useful when you have more than one of these inverters connected at the same time. I tried to set up exactly this scenario this weekend (two identical 1200W inverters in parallel on the same RS485 bus), however, the result isn't what I was expecting:

The relevant parts of my ESPHome config are:
``` yaml
soyosource_virtual_meter:
  power_id: powermeter
  min_power_demand: 0
  max_power_demand: 1800
  power_demand_divider: 2
  buffer: -3
  power_sensor_inactivity_timeout: 20s
  power_demand_calculation: NEGATIVE_MEASUREMENTS_REQUIRED
```

Everything works as it should except that **the maximum power demand cannot exceed 900 Watt** (resulting in both of the inverters doing a 450 W each). Obviously, the whole idea of installing more than one inverter is getting more than 900 W, though.

This leads me to the conclusion that `max_power_demand` (set to `1800` as above), is not accepted and the default value of 900
https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/blob/6a5c59fd792cd6a1cce19f5ae31d4ad3875a7478/components/soyosource_virtual_meter/__init__.py#L22
https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/blob/6a5c59fd792cd6a1cce19f5ae31d4ad3875a7478/components/soyosource_virtual_meter/__init__.py#L71-L73
is still used.

This is confirmed by (a) a red border around the input field telling me on hover me that values larger than 900 aren't allowed:
![Screenshot from 2022-10-01 12-03-15](https://user-images.githubusercontent.com/16748619/193404180-62b9308b-81c7-4469-87fc-3843dccd3850.png)

and (b) by launching a dedicated web server on the very same device:

Indeed, when adding
``` yaml
web_server:
  port: 80
```
showing that the maximum of the slider is still at 900:

![Screenshot from 2022-10-01 12-07-52](https://user-images.githubusercontent.com/16748619/193404300-19e9f0fd-1725-4d5b-8c99-0d9ec9295dfd.png)

**Comment by syssi** [comment]
Good catch! I will have a look and change the limits. 73 de DO2KSM

**Comment by syssi** [comment]
I've prepare a fix to increase the hard limits. Please adjust your configuration slightly:

```
soyosource_virtual_meter:
  power_id: powermeter
  min_power_demand: 0
  max_power_demand: 1800
  power_demand_divider: 2
  buffer: -3
  power_sensor_inactivity_timeout: 20s
  power_demand_calculation: NEGATIVE_MEASUREMENTS_REQUIRED

number:
  - platform: soyosource_virtual_meter
    manual_power_demand:
      name: "${name} manual power demand"
      max_value: 1800
    max_power_demand:
      name: "${name} max power demand"
      initial_value: 600
      max_value: 1800
      restore_value: true
```
